### PR TITLE
FLUID-6333: New icons for Word Spacing

### PR DESCRIPTION
**Pull request by jhung**
@jobara want to take a look and see if it's fine for your use?

### CODE REVIEW

**Comment by jobara** [comment]
@jhung could you do a small bit of cleanup.. can you remove the package-lock.json file and add it to the gitignore?

**Comment by jhung** [comment]
@jobara Deleted and added to .gitignore

**Comment by jobara** [comment]
@jhung we had talked about harmonizing the arrows used for spacing icons. In particular those for the character spacing. Would you be able to update those icons as well?

**Comment by jobara** [comment]
@jhung should the character-spacing-condensed.svg file be minified?

**Comment by jhung** [comment]
@jobara should be minified now. Thanks for catching that.

**Comment by jobara** [comment]
merged at a14272979e6ce485a73a54d133653c11bb649cb3

**Pull request merged**
